// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cam_service.proto
// Protobuf C++ Version: 6.33.4

#ifndef cam_5fservice_2eproto_2epb_2eh
#define cam_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cam_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cam_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_cam_5fservice_2eproto;
}  // extern "C"
namespace cam {
class CalculationRequest;
struct CalculationRequestDefaultTypeInternal;
extern CalculationRequestDefaultTypeInternal _CalculationRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CalculationRequest_class_data_;
class CalculationResponse;
struct CalculationResponseDefaultTypeInternal;
extern CalculationResponseDefaultTypeInternal _CalculationResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CalculationResponse_class_data_;
class SurfaceCalculationRequest;
struct SurfaceCalculationRequestDefaultTypeInternal;
extern SurfaceCalculationRequestDefaultTypeInternal _SurfaceCalculationRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SurfaceCalculationRequest_class_data_;
}  // namespace cam
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace cam {

// ===================================================================


// -------------------------------------------------------------------

class SurfaceCalculationRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cam.SurfaceCalculationRequest) */ {
 public:
  inline SurfaceCalculationRequest() : SurfaceCalculationRequest(nullptr) {}
  ~SurfaceCalculationRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SurfaceCalculationRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SurfaceCalculationRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SurfaceCalculationRequest(::google::protobuf::internal::ConstantInitialized);

  inline SurfaceCalculationRequest(const SurfaceCalculationRequest& from) : SurfaceCalculationRequest(nullptr, from) {}
  inline SurfaceCalculationRequest(SurfaceCalculationRequest&& from) noexcept
      : SurfaceCalculationRequest(nullptr, ::std::move(from)) {}
  inline SurfaceCalculationRequest& operator=(const SurfaceCalculationRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SurfaceCalculationRequest& operator=(SurfaceCalculationRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SurfaceCalculationRequest& default_instance() {
    return *reinterpret_cast<const SurfaceCalculationRequest*>(
        &_SurfaceCalculationRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SurfaceCalculationRequest& a, SurfaceCalculationRequest& b) { a.Swap(&b); }
  inline void Swap(SurfaceCalculationRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SurfaceCalculationRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SurfaceCalculationRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SurfaceCalculationRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SurfaceCalculationRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SurfaceCalculationRequest& from) { SurfaceCalculationRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SurfaceCalculationRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cam.SurfaceCalculationRequest"; }

  explicit SurfaceCalculationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SurfaceCalculationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SurfaceCalculationRequest& from);
  SurfaceCalculationRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SurfaceCalculationRequest&& from) noexcept
      : SurfaceCalculationRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStepDataFieldNumber = 1,
    kModelHashFieldNumber = 8,
    kStepUFieldNumber = 2,
    kStepVFieldNumber = 3,
    kToolpathModeFieldNumber = 4,
    kNumPathsFieldNumber = 5,
    kStartDirectionFieldNumber = 6,
    kFaceIndexFieldNumber = 7,
  };
  // bytes step_data = 1;
  void clear_step_data() ;
  const ::std::string& step_data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_step_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_step_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_step_data();
  void set_allocated_step_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_step_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_step_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_step_data();

  public:
  // string model_hash = 8;
  void clear_model_hash() ;
  const ::std::string& model_hash() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_model_hash(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_model_hash();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_model_hash();
  void set_allocated_model_hash(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_model_hash() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_model_hash(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_model_hash();

  public:
  // double step_u = 2;
  void clear_step_u() ;
  double step_u() const;
  void set_step_u(double value);

  private:
  double _internal_step_u() const;
  void _internal_set_step_u(double value);

  public:
  // double step_v = 3;
  void clear_step_v() ;
  double step_v() const;
  void set_step_v(double value);

  private:
  double _internal_step_v() const;
  void _internal_set_step_v(double value);

  public:
  // int32 toolpath_mode = 4;
  void clear_toolpath_mode() ;
  ::int32_t toolpath_mode() const;
  void set_toolpath_mode(::int32_t value);

  private:
  ::int32_t _internal_toolpath_mode() const;
  void _internal_set_toolpath_mode(::int32_t value);

  public:
  // int32 num_paths = 5;
  void clear_num_paths() ;
  ::int32_t num_paths() const;
  void set_num_paths(::int32_t value);

  private:
  ::int32_t _internal_num_paths() const;
  void _internal_set_num_paths(::int32_t value);

  public:
  // int32 start_direction = 6;
  void clear_start_direction() ;
  ::int32_t start_direction() const;
  void set_start_direction(::int32_t value);

  private:
  ::int32_t _internal_start_direction() const;
  void _internal_set_start_direction(::int32_t value);

  public:
  // int32 face_index = 7;
  void clear_face_index() ;
  ::int32_t face_index() const;
  void set_face_index(::int32_t value);

  private:
  ::int32_t _internal_face_index() const;
  void _internal_set_face_index(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:cam.SurfaceCalculationRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 56,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SurfaceCalculationRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr step_data_;
    ::google::protobuf::internal::ArenaStringPtr model_hash_;
    double step_u_;
    double step_v_;
    ::int32_t toolpath_mode_;
    ::int32_t num_paths_;
    ::int32_t start_direction_;
    ::int32_t face_index_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cam_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SurfaceCalculationRequest_class_data_;
// -------------------------------------------------------------------

class CalculationResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cam.CalculationResponse) */ {
 public:
  inline CalculationResponse() : CalculationResponse(nullptr) {}
  ~CalculationResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CalculationResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CalculationResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CalculationResponse(::google::protobuf::internal::ConstantInitialized);

  inline CalculationResponse(const CalculationResponse& from) : CalculationResponse(nullptr, from) {}
  inline CalculationResponse(CalculationResponse&& from) noexcept
      : CalculationResponse(nullptr, ::std::move(from)) {}
  inline CalculationResponse& operator=(const CalculationResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalculationResponse& operator=(CalculationResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CalculationResponse& default_instance() {
    return *reinterpret_cast<const CalculationResponse*>(
        &_CalculationResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CalculationResponse& a, CalculationResponse& b) { a.Swap(&b); }
  inline void Swap(CalculationResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalculationResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CalculationResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CalculationResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CalculationResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CalculationResponse& from) { CalculationResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CalculationResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cam.CalculationResponse"; }

  explicit CalculationResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CalculationResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CalculationResponse& from);
  CalculationResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CalculationResponse&& from) noexcept
      : CalculationResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRawVerticesFieldNumber = 1,
    kPointCountFieldNumber = 2,
  };
  // bytes raw_vertices = 1;
  void clear_raw_vertices() ;
  const ::std::string& raw_vertices() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_raw_vertices(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_raw_vertices();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_raw_vertices();
  void set_allocated_raw_vertices(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_raw_vertices() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_raw_vertices(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_raw_vertices();

  public:
  // int32 point_count = 2;
  void clear_point_count() ;
  ::int32_t point_count() const;
  void set_point_count(::int32_t value);

  private:
  ::int32_t _internal_point_count() const;
  void _internal_set_point_count(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:cam.CalculationResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CalculationResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr raw_vertices_;
    ::int32_t point_count_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cam_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CalculationResponse_class_data_;
// -------------------------------------------------------------------

class CalculationRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cam.CalculationRequest) */ {
 public:
  inline CalculationRequest() : CalculationRequest(nullptr) {}
  ~CalculationRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CalculationRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CalculationRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CalculationRequest(::google::protobuf::internal::ConstantInitialized);

  inline CalculationRequest(const CalculationRequest& from) : CalculationRequest(nullptr, from) {}
  inline CalculationRequest(CalculationRequest&& from) noexcept
      : CalculationRequest(nullptr, ::std::move(from)) {}
  inline CalculationRequest& operator=(const CalculationRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalculationRequest& operator=(CalculationRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CalculationRequest& default_instance() {
    return *reinterpret_cast<const CalculationRequest*>(
        &_CalculationRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CalculationRequest& a, CalculationRequest& b) { a.Swap(&b); }
  inline void Swap(CalculationRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalculationRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CalculationRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CalculationRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CalculationRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CalculationRequest& from) { CalculationRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CalculationRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cam.CalculationRequest"; }

  explicit CalculationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CalculationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CalculationRequest& from);
  CalculationRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CalculationRequest&& from) noexcept
      : CalculationRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXMinFieldNumber = 1,
    kXMaxFieldNumber = 2,
    kYMinFieldNumber = 3,
    kYMaxFieldNumber = 4,
    kZMaxFieldNumber = 5,
  };
  // double X_min = 1;
  void clear_x_min() ;
  double x_min() const;
  void set_x_min(double value);

  private:
  double _internal_x_min() const;
  void _internal_set_x_min(double value);

  public:
  // double X_max = 2;
  void clear_x_max() ;
  double x_max() const;
  void set_x_max(double value);

  private:
  double _internal_x_max() const;
  void _internal_set_x_max(double value);

  public:
  // double Y_min = 3;
  void clear_y_min() ;
  double y_min() const;
  void set_y_min(double value);

  private:
  double _internal_y_min() const;
  void _internal_set_y_min(double value);

  public:
  // double Y_max = 4;
  void clear_y_max() ;
  double y_max() const;
  void set_y_max(double value);

  private:
  double _internal_y_max() const;
  void _internal_set_y_max(double value);

  public:
  // double Z_max = 5;
  void clear_z_max() ;
  double z_max() const;
  void set_z_max(double value);

  private:
  double _internal_z_max() const;
  void _internal_set_z_max(double value);

  public:
  // @@protoc_insertion_point(class_scope:cam.CalculationRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CalculationRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double x_min_;
    double x_max_;
    double y_min_;
    double y_max_;
    double z_max_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cam_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CalculationRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CalculationRequest

// double X_min = 1;
inline void CalculationRequest::clear_x_min() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_min_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double CalculationRequest::x_min() const {
  // @@protoc_insertion_point(field_get:cam.CalculationRequest.X_min)
  return _internal_x_min();
}
inline void CalculationRequest::set_x_min(double value) {
  _internal_set_x_min(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:cam.CalculationRequest.X_min)
}
inline double CalculationRequest::_internal_x_min() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_min_;
}
inline void CalculationRequest::_internal_set_x_min(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_min_ = value;
}

// double X_max = 2;
inline void CalculationRequest::clear_x_max() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_max_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double CalculationRequest::x_max() const {
  // @@protoc_insertion_point(field_get:cam.CalculationRequest.X_max)
  return _internal_x_max();
}
inline void CalculationRequest::set_x_max(double value) {
  _internal_set_x_max(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:cam.CalculationRequest.X_max)
}
inline double CalculationRequest::_internal_x_max() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_max_;
}
inline void CalculationRequest::_internal_set_x_max(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_max_ = value;
}

// double Y_min = 3;
inline void CalculationRequest::clear_y_min() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_min_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double CalculationRequest::y_min() const {
  // @@protoc_insertion_point(field_get:cam.CalculationRequest.Y_min)
  return _internal_y_min();
}
inline void CalculationRequest::set_y_min(double value) {
  _internal_set_y_min(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:cam.CalculationRequest.Y_min)
}
inline double CalculationRequest::_internal_y_min() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_min_;
}
inline void CalculationRequest::_internal_set_y_min(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_min_ = value;
}

// double Y_max = 4;
inline void CalculationRequest::clear_y_max() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_max_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double CalculationRequest::y_max() const {
  // @@protoc_insertion_point(field_get:cam.CalculationRequest.Y_max)
  return _internal_y_max();
}
inline void CalculationRequest::set_y_max(double value) {
  _internal_set_y_max(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:cam.CalculationRequest.Y_max)
}
inline double CalculationRequest::_internal_y_max() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_max_;
}
inline void CalculationRequest::_internal_set_y_max(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_max_ = value;
}

// double Z_max = 5;
inline void CalculationRequest::clear_z_max() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_max_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline double CalculationRequest::z_max() const {
  // @@protoc_insertion_point(field_get:cam.CalculationRequest.Z_max)
  return _internal_z_max();
}
inline void CalculationRequest::set_z_max(double value) {
  _internal_set_z_max(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:cam.CalculationRequest.Z_max)
}
inline double CalculationRequest::_internal_z_max() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_max_;
}
inline void CalculationRequest::_internal_set_z_max(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_max_ = value;
}

// -------------------------------------------------------------------

// SurfaceCalculationRequest

// bytes step_data = 1;
inline void SurfaceCalculationRequest::clear_step_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.step_data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& SurfaceCalculationRequest::step_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cam.SurfaceCalculationRequest.step_data)
  return _internal_step_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SurfaceCalculationRequest::set_step_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.step_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cam.SurfaceCalculationRequest.step_data)
}
inline ::std::string* PROTOBUF_NONNULL SurfaceCalculationRequest::mutable_step_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_step_data();
  // @@protoc_insertion_point(field_mutable:cam.SurfaceCalculationRequest.step_data)
  return _s;
}
inline const ::std::string& SurfaceCalculationRequest::_internal_step_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.step_data_.Get();
}
inline void SurfaceCalculationRequest::_internal_set_step_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.step_data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SurfaceCalculationRequest::_internal_mutable_step_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.step_data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SurfaceCalculationRequest::release_step_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cam.SurfaceCalculationRequest.step_data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.step_data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.step_data_.Set("", GetArena());
  }
  return released;
}
inline void SurfaceCalculationRequest::set_allocated_step_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.step_data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.step_data_.IsDefault()) {
    _impl_.step_data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:cam.SurfaceCalculationRequest.step_data)
}

// double step_u = 2;
inline void SurfaceCalculationRequest::clear_step_u() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.step_u_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double SurfaceCalculationRequest::step_u() const {
  // @@protoc_insertion_point(field_get:cam.SurfaceCalculationRequest.step_u)
  return _internal_step_u();
}
inline void SurfaceCalculationRequest::set_step_u(double value) {
  _internal_set_step_u(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:cam.SurfaceCalculationRequest.step_u)
}
inline double SurfaceCalculationRequest::_internal_step_u() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.step_u_;
}
inline void SurfaceCalculationRequest::_internal_set_step_u(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.step_u_ = value;
}

// double step_v = 3;
inline void SurfaceCalculationRequest::clear_step_v() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.step_v_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double SurfaceCalculationRequest::step_v() const {
  // @@protoc_insertion_point(field_get:cam.SurfaceCalculationRequest.step_v)
  return _internal_step_v();
}
inline void SurfaceCalculationRequest::set_step_v(double value) {
  _internal_set_step_v(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:cam.SurfaceCalculationRequest.step_v)
}
inline double SurfaceCalculationRequest::_internal_step_v() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.step_v_;
}
inline void SurfaceCalculationRequest::_internal_set_step_v(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.step_v_ = value;
}

// int32 toolpath_mode = 4;
inline void SurfaceCalculationRequest::clear_toolpath_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.toolpath_mode_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t SurfaceCalculationRequest::toolpath_mode() const {
  // @@protoc_insertion_point(field_get:cam.SurfaceCalculationRequest.toolpath_mode)
  return _internal_toolpath_mode();
}
inline void SurfaceCalculationRequest::set_toolpath_mode(::int32_t value) {
  _internal_set_toolpath_mode(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:cam.SurfaceCalculationRequest.toolpath_mode)
}
inline ::int32_t SurfaceCalculationRequest::_internal_toolpath_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.toolpath_mode_;
}
inline void SurfaceCalculationRequest::_internal_set_toolpath_mode(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.toolpath_mode_ = value;
}

// int32 num_paths = 5;
inline void SurfaceCalculationRequest::clear_num_paths() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_paths_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t SurfaceCalculationRequest::num_paths() const {
  // @@protoc_insertion_point(field_get:cam.SurfaceCalculationRequest.num_paths)
  return _internal_num_paths();
}
inline void SurfaceCalculationRequest::set_num_paths(::int32_t value) {
  _internal_set_num_paths(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:cam.SurfaceCalculationRequest.num_paths)
}
inline ::int32_t SurfaceCalculationRequest::_internal_num_paths() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_paths_;
}
inline void SurfaceCalculationRequest::_internal_set_num_paths(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_paths_ = value;
}

// int32 start_direction = 6;
inline void SurfaceCalculationRequest::clear_start_direction() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_direction_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t SurfaceCalculationRequest::start_direction() const {
  // @@protoc_insertion_point(field_get:cam.SurfaceCalculationRequest.start_direction)
  return _internal_start_direction();
}
inline void SurfaceCalculationRequest::set_start_direction(::int32_t value) {
  _internal_set_start_direction(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:cam.SurfaceCalculationRequest.start_direction)
}
inline ::int32_t SurfaceCalculationRequest::_internal_start_direction() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_direction_;
}
inline void SurfaceCalculationRequest::_internal_set_start_direction(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_direction_ = value;
}

// int32 face_index = 7;
inline void SurfaceCalculationRequest::clear_face_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.face_index_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::int32_t SurfaceCalculationRequest::face_index() const {
  // @@protoc_insertion_point(field_get:cam.SurfaceCalculationRequest.face_index)
  return _internal_face_index();
}
inline void SurfaceCalculationRequest::set_face_index(::int32_t value) {
  _internal_set_face_index(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:cam.SurfaceCalculationRequest.face_index)
}
inline ::int32_t SurfaceCalculationRequest::_internal_face_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.face_index_;
}
inline void SurfaceCalculationRequest::_internal_set_face_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.face_index_ = value;
}

// string model_hash = 8;
inline void SurfaceCalculationRequest::clear_model_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_hash_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& SurfaceCalculationRequest::model_hash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cam.SurfaceCalculationRequest.model_hash)
  return _internal_model_hash();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SurfaceCalculationRequest::set_model_hash(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.model_hash_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cam.SurfaceCalculationRequest.model_hash)
}
inline ::std::string* PROTOBUF_NONNULL SurfaceCalculationRequest::mutable_model_hash()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_model_hash();
  // @@protoc_insertion_point(field_mutable:cam.SurfaceCalculationRequest.model_hash)
  return _s;
}
inline const ::std::string& SurfaceCalculationRequest::_internal_model_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.model_hash_.Get();
}
inline void SurfaceCalculationRequest::_internal_set_model_hash(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_hash_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SurfaceCalculationRequest::_internal_mutable_model_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.model_hash_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SurfaceCalculationRequest::release_model_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cam.SurfaceCalculationRequest.model_hash)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.model_hash_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.model_hash_.Set("", GetArena());
  }
  return released;
}
inline void SurfaceCalculationRequest::set_allocated_model_hash(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.model_hash_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.model_hash_.IsDefault()) {
    _impl_.model_hash_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:cam.SurfaceCalculationRequest.model_hash)
}

// -------------------------------------------------------------------

// CalculationResponse

// bytes raw_vertices = 1;
inline void CalculationResponse::clear_raw_vertices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.raw_vertices_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CalculationResponse::raw_vertices() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cam.CalculationResponse.raw_vertices)
  return _internal_raw_vertices();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CalculationResponse::set_raw_vertices(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.raw_vertices_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cam.CalculationResponse.raw_vertices)
}
inline ::std::string* PROTOBUF_NONNULL CalculationResponse::mutable_raw_vertices()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_raw_vertices();
  // @@protoc_insertion_point(field_mutable:cam.CalculationResponse.raw_vertices)
  return _s;
}
inline const ::std::string& CalculationResponse::_internal_raw_vertices() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.raw_vertices_.Get();
}
inline void CalculationResponse::_internal_set_raw_vertices(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.raw_vertices_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CalculationResponse::_internal_mutable_raw_vertices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.raw_vertices_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CalculationResponse::release_raw_vertices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cam.CalculationResponse.raw_vertices)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.raw_vertices_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.raw_vertices_.Set("", GetArena());
  }
  return released;
}
inline void CalculationResponse::set_allocated_raw_vertices(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.raw_vertices_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.raw_vertices_.IsDefault()) {
    _impl_.raw_vertices_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:cam.CalculationResponse.raw_vertices)
}

// int32 point_count = 2;
inline void CalculationResponse::clear_point_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point_count_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t CalculationResponse::point_count() const {
  // @@protoc_insertion_point(field_get:cam.CalculationResponse.point_count)
  return _internal_point_count();
}
inline void CalculationResponse::set_point_count(::int32_t value) {
  _internal_set_point_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:cam.CalculationResponse.point_count)
}
inline ::int32_t CalculationResponse::_internal_point_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point_count_;
}
inline void CalculationResponse::_internal_set_point_count(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point_count_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace cam


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // cam_5fservice_2eproto_2epb_2eh
