// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cam_service.proto

#include "cam_service.pb.h"
#include "cam_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace cam {

static const char* CamCalculationService_method_names[] = {
  "/cam.CamCalculationService/CalculateToolpath",
  "/cam.CamCalculationService/CalculateSurfaceToolpath",
};

std::unique_ptr< CamCalculationService::Stub> CamCalculationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CamCalculationService::Stub> stub(new CamCalculationService::Stub(channel, options));
  return stub;
}

CamCalculationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CalculateToolpath_(CamCalculationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CalculateSurfaceToolpath_(CamCalculationService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CamCalculationService::Stub::CalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::cam::CalculationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::cam::CalculationRequest, ::cam::CalculationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CalculateToolpath_, context, request, response);
}

void CamCalculationService::Stub::async::CalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest* request, ::cam::CalculationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::cam::CalculationRequest, ::cam::CalculationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateToolpath_, context, request, response, std::move(f));
}

void CamCalculationService::Stub::async::CalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest* request, ::cam::CalculationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateToolpath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>* CamCalculationService::Stub::PrepareAsyncCalculateToolpathRaw(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::cam::CalculationResponse, ::cam::CalculationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CalculateToolpath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>* CamCalculationService::Stub::AsyncCalculateToolpathRaw(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCalculateToolpathRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CamCalculationService::Stub::CalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::cam::CalculationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::cam::SurfaceCalculationRequest, ::cam::CalculationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CalculateSurfaceToolpath_, context, request, response);
}

void CamCalculationService::Stub::async::CalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest* request, ::cam::CalculationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::cam::SurfaceCalculationRequest, ::cam::CalculationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateSurfaceToolpath_, context, request, response, std::move(f));
}

void CamCalculationService::Stub::async::CalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest* request, ::cam::CalculationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateSurfaceToolpath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>* CamCalculationService::Stub::PrepareAsyncCalculateSurfaceToolpathRaw(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::cam::CalculationResponse, ::cam::SurfaceCalculationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CalculateSurfaceToolpath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>* CamCalculationService::Stub::AsyncCalculateSurfaceToolpathRaw(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCalculateSurfaceToolpathRaw(context, request, cq);
  result->StartCall();
  return result;
}

CamCalculationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CamCalculationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CamCalculationService::Service, ::cam::CalculationRequest, ::cam::CalculationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CamCalculationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::cam::CalculationRequest* req,
             ::cam::CalculationResponse* resp) {
               return service->CalculateToolpath(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CamCalculationService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CamCalculationService::Service, ::cam::SurfaceCalculationRequest, ::cam::CalculationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CamCalculationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::cam::SurfaceCalculationRequest* req,
             ::cam::CalculationResponse* resp) {
               return service->CalculateSurfaceToolpath(ctx, req, resp);
             }, this)));
}

CamCalculationService::Service::~Service() {
}

::grpc::Status CamCalculationService::Service::CalculateToolpath(::grpc::ServerContext* context, const ::cam::CalculationRequest* request, ::cam::CalculationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CamCalculationService::Service::CalculateSurfaceToolpath(::grpc::ServerContext* context, const ::cam::SurfaceCalculationRequest* request, ::cam::CalculationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace cam
#include <grpcpp/ports_undef.inc>

