// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cam_service.proto
// Protobuf C++ Version: 6.33.4

#include "cam_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace cam {

inline constexpr SurfaceCalculationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        step_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        step_u_{0},
        step_v_{0},
        toolpath_mode_{0},
        num_paths_{0},
        start_direction_{0},
        face_index_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SurfaceCalculationRequest::SurfaceCalculationRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SurfaceCalculationRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SurfaceCalculationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SurfaceCalculationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SurfaceCalculationRequestDefaultTypeInternal() {}
  union {
    SurfaceCalculationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SurfaceCalculationRequestDefaultTypeInternal _SurfaceCalculationRequest_default_instance_;

inline constexpr CalculationResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        raw_vertices_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        point_count_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CalculationResponse::CalculationResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CalculationResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CalculationResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CalculationResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CalculationResponseDefaultTypeInternal() {}
  union {
    CalculationResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CalculationResponseDefaultTypeInternal _CalculationResponse_default_instance_;

inline constexpr CalculationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        x_min_{0},
        x_max_{0},
        y_min_{0},
        y_max_{0},
        z_max_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CalculationRequest::CalculationRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CalculationRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CalculationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CalculationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CalculationRequestDefaultTypeInternal() {}
  union {
    CalculationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CalculationRequestDefaultTypeInternal _CalculationRequest_default_instance_;
}  // namespace cam
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_cam_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_cam_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_cam_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::cam::CalculationRequest, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::cam::CalculationRequest, _impl_.x_min_),
        PROTOBUF_FIELD_OFFSET(::cam::CalculationRequest, _impl_.x_max_),
        PROTOBUF_FIELD_OFFSET(::cam::CalculationRequest, _impl_.y_min_),
        PROTOBUF_FIELD_OFFSET(::cam::CalculationRequest, _impl_.y_max_),
        PROTOBUF_FIELD_OFFSET(::cam::CalculationRequest, _impl_.z_max_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::cam::SurfaceCalculationRequest, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::cam::SurfaceCalculationRequest, _impl_.step_data_),
        PROTOBUF_FIELD_OFFSET(::cam::SurfaceCalculationRequest, _impl_.step_u_),
        PROTOBUF_FIELD_OFFSET(::cam::SurfaceCalculationRequest, _impl_.step_v_),
        PROTOBUF_FIELD_OFFSET(::cam::SurfaceCalculationRequest, _impl_.toolpath_mode_),
        PROTOBUF_FIELD_OFFSET(::cam::SurfaceCalculationRequest, _impl_.num_paths_),
        PROTOBUF_FIELD_OFFSET(::cam::SurfaceCalculationRequest, _impl_.start_direction_),
        PROTOBUF_FIELD_OFFSET(::cam::SurfaceCalculationRequest, _impl_.face_index_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::cam::CalculationResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::cam::CalculationResponse, _impl_.raw_vertices_),
        PROTOBUF_FIELD_OFFSET(::cam::CalculationResponse, _impl_.point_count_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::cam::CalculationRequest)},
        {13, sizeof(::cam::SurfaceCalculationRequest)},
        {30, sizeof(::cam::CalculationResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::cam::_CalculationRequest_default_instance_._instance,
    &::cam::_SurfaceCalculationRequest_default_instance_._instance,
    &::cam::_CalculationResponse_default_instance_._instance,
};
const char descriptor_table_protodef_cam_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021cam_service.proto\022\003cam\"_\n\022CalculationR"
    "equest\022\r\n\005X_min\030\001 \001(\001\022\r\n\005X_max\030\002 \001(\001\022\r\n\005"
    "Y_min\030\003 \001(\001\022\r\n\005Y_max\030\004 \001(\001\022\r\n\005Z_max\030\005 \001("
    "\001\"\245\001\n\031SurfaceCalculationRequest\022\021\n\tstep_"
    "data\030\001 \001(\014\022\016\n\006step_u\030\002 \001(\001\022\016\n\006step_v\030\003 \001"
    "(\001\022\025\n\rtoolpath_mode\030\004 \001(\005\022\021\n\tnum_paths\030\005"
    " \001(\005\022\027\n\017start_direction\030\006 \001(\005\022\022\n\nface_in"
    "dex\030\007 \001(\005\"@\n\023CalculationResponse\022\024\n\014raw_"
    "vertices\030\001 \001(\014\022\023\n\013point_count\030\002 \001(\0052\265\001\n\025"
    "CamCalculationService\022F\n\021CalculateToolpa"
    "th\022\027.cam.CalculationRequest\032\030.cam.Calcul"
    "ationResponse\022T\n\030CalculateSurfaceToolpat"
    "h\022\036.cam.SurfaceCalculationRequest\032\030.cam."
    "CalculationResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_cam_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cam_5fservice_2eproto = {
    false,
    false,
    547,
    descriptor_table_protodef_cam_5fservice_2eproto,
    "cam_service.proto",
    &descriptor_table_cam_5fservice_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_cam_5fservice_2eproto::offsets,
    file_level_enum_descriptors_cam_5fservice_2eproto,
    file_level_service_descriptors_cam_5fservice_2eproto,
};
namespace cam {
// ===================================================================

class CalculationRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CalculationRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_._has_bits_);
};

CalculationRequest::CalculationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CalculationRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cam.CalculationRequest)
}
CalculationRequest::CalculationRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CalculationRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CalculationRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CalculationRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CalculationRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, x_min_),
           0,
           offsetof(Impl_, z_max_) -
               offsetof(Impl_, x_min_) +
               sizeof(Impl_::z_max_));
}
CalculationRequest::~CalculationRequest() {
  // @@protoc_insertion_point(destructor:cam.CalculationRequest)
  SharedDtor(*this);
}
inline void CalculationRequest::SharedDtor(MessageLite& self) {
  CalculationRequest& this_ = static_cast<CalculationRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CalculationRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CalculationRequest(arena);
}
constexpr auto CalculationRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CalculationRequest),
                                            alignof(CalculationRequest));
}
constexpr auto CalculationRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CalculationRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CalculationRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CalculationRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CalculationRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CalculationRequest>(), &CalculationRequest::ByteSizeLong,
              &CalculationRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_._cached_size_),
          false,
      },
      &CalculationRequest::kDescriptorMethods,
      &descriptor_table_cam_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CalculationRequest_class_data_ =
        CalculationRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CalculationRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CalculationRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CalculationRequest_class_data_.tc_table);
  return CalculationRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
CalculationRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CalculationRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cam::CalculationRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double X_min = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 0, 0,
      PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.x_min_)}},
    // double X_max = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0,
      PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.x_max_)}},
    // double Y_min = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 2, 0,
      PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.y_min_)}},
    // double Y_max = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 3, 0,
      PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.y_max_)}},
    // double Z_max = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 4, 0,
      PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.z_max_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // double X_min = 1;
    {PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.x_min_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double X_max = 2;
    {PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.x_max_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double Y_min = 3;
    {PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.y_min_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double Y_max = 4;
    {PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.y_max_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double Z_max = 5;
    {PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.z_max_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CalculationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:cam.CalculationRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    ::memset(&_impl_.x_min_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.z_max_) -
        reinterpret_cast<char*>(&_impl_.x_min_)) + sizeof(_impl_.z_max_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CalculationRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CalculationRequest& this_ = static_cast<const CalculationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CalculationRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CalculationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:cam.CalculationRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // double X_min = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_x_min()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          1, this_._internal_x_min(), target);
    }
  }

  // double X_max = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_x_max()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_x_max(), target);
    }
  }

  // double Y_min = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_y_min()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this_._internal_y_min(), target);
    }
  }

  // double Y_max = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_y_max()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          4, this_._internal_y_max(), target);
    }
  }

  // double Z_max = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_z_max()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          5, this_._internal_z_max(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cam.CalculationRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CalculationRequest::ByteSizeLong(const MessageLite& base) {
  const CalculationRequest& this_ = static_cast<const CalculationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CalculationRequest::ByteSizeLong() const {
  const CalculationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cam.CalculationRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // double X_min = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_x_min()) != 0) {
        total_size += 9;
      }
    }
    // double X_max = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_x_max()) != 0) {
        total_size += 9;
      }
    }
    // double Y_min = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_y_min()) != 0) {
        total_size += 9;
      }
    }
    // double Y_max = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_y_max()) != 0) {
        total_size += 9;
      }
    }
    // double Z_max = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_z_max()) != 0) {
        total_size += 9;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CalculationRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CalculationRequest*>(&to_msg);
  auto& from = static_cast<const CalculationRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:cam.CalculationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_x_min()) != 0) {
        _this->_impl_.x_min_ = from._impl_.x_min_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_x_max()) != 0) {
        _this->_impl_.x_max_ = from._impl_.x_max_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_y_min()) != 0) {
        _this->_impl_.y_min_ = from._impl_.y_min_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_y_max()) != 0) {
        _this->_impl_.y_max_ = from._impl_.y_max_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_z_max()) != 0) {
        _this->_impl_.z_max_ = from._impl_.z_max_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CalculationRequest::CopyFrom(const CalculationRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:cam.CalculationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CalculationRequest::InternalSwap(CalculationRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.z_max_)
      + sizeof(CalculationRequest::_impl_.z_max_)
      - PROTOBUF_FIELD_OFFSET(CalculationRequest, _impl_.x_min_)>(
          reinterpret_cast<char*>(&_impl_.x_min_),
          reinterpret_cast<char*>(&other->_impl_.x_min_));
}

::google::protobuf::Metadata CalculationRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SurfaceCalculationRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SurfaceCalculationRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_._has_bits_);
};

SurfaceCalculationRequest::SurfaceCalculationRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SurfaceCalculationRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cam.SurfaceCalculationRequest)
}
PROTOBUF_NDEBUG_INLINE SurfaceCalculationRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::cam::SurfaceCalculationRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        step_data_(arena, from.step_data_) {}

SurfaceCalculationRequest::SurfaceCalculationRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SurfaceCalculationRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SurfaceCalculationRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SurfaceCalculationRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, step_u_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, step_u_),
           offsetof(Impl_, face_index_) -
               offsetof(Impl_, step_u_) +
               sizeof(Impl_::face_index_));

  // @@protoc_insertion_point(copy_constructor:cam.SurfaceCalculationRequest)
}
PROTOBUF_NDEBUG_INLINE SurfaceCalculationRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        step_data_(arena) {}

inline void SurfaceCalculationRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, step_u_),
           0,
           offsetof(Impl_, face_index_) -
               offsetof(Impl_, step_u_) +
               sizeof(Impl_::face_index_));
}
SurfaceCalculationRequest::~SurfaceCalculationRequest() {
  // @@protoc_insertion_point(destructor:cam.SurfaceCalculationRequest)
  SharedDtor(*this);
}
inline void SurfaceCalculationRequest::SharedDtor(MessageLite& self) {
  SurfaceCalculationRequest& this_ = static_cast<SurfaceCalculationRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.step_data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SurfaceCalculationRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SurfaceCalculationRequest(arena);
}
constexpr auto SurfaceCalculationRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SurfaceCalculationRequest),
                                            alignof(SurfaceCalculationRequest));
}
constexpr auto SurfaceCalculationRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SurfaceCalculationRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SurfaceCalculationRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SurfaceCalculationRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SurfaceCalculationRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SurfaceCalculationRequest>(), &SurfaceCalculationRequest::ByteSizeLong,
              &SurfaceCalculationRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_._cached_size_),
          false,
      },
      &SurfaceCalculationRequest::kDescriptorMethods,
      &descriptor_table_cam_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SurfaceCalculationRequest_class_data_ =
        SurfaceCalculationRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SurfaceCalculationRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SurfaceCalculationRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SurfaceCalculationRequest_class_data_.tc_table);
  return SurfaceCalculationRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 0, 2>
SurfaceCalculationRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SurfaceCalculationRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cam::SurfaceCalculationRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes step_data = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.step_data_)}},
    // double step_u = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0,
      PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.step_u_)}},
    // double step_v = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 2, 0,
      PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.step_v_)}},
    // int32 toolpath_mode = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SurfaceCalculationRequest, _impl_.toolpath_mode_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.toolpath_mode_)}},
    // int32 num_paths = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SurfaceCalculationRequest, _impl_.num_paths_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.num_paths_)}},
    // int32 start_direction = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SurfaceCalculationRequest, _impl_.start_direction_), 5>(),
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.start_direction_)}},
    // int32 face_index = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SurfaceCalculationRequest, _impl_.face_index_), 6>(),
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.face_index_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes step_data = 1;
    {PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.step_data_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // double step_u = 2;
    {PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.step_u_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double step_v = 3;
    {PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.step_v_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // int32 toolpath_mode = 4;
    {PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.toolpath_mode_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 num_paths = 5;
    {PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.num_paths_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 start_direction = 6;
    {PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.start_direction_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 face_index = 7;
    {PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.face_index_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SurfaceCalculationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:cam.SurfaceCalculationRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.step_data_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000007eU)) {
    ::memset(&_impl_.step_u_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.face_index_) -
        reinterpret_cast<char*>(&_impl_.step_u_)) + sizeof(_impl_.face_index_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SurfaceCalculationRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SurfaceCalculationRequest& this_ = static_cast<const SurfaceCalculationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SurfaceCalculationRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SurfaceCalculationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:cam.SurfaceCalculationRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes step_data = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_step_data().empty()) {
      const ::std::string& _s = this_._internal_step_data();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // double step_u = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_step_u()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_step_u(), target);
    }
  }

  // double step_v = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_step_v()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this_._internal_step_v(), target);
    }
  }

  // int32 toolpath_mode = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_toolpath_mode() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_toolpath_mode(), target);
    }
  }

  // int32 num_paths = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_num_paths() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
              stream, this_._internal_num_paths(), target);
    }
  }

  // int32 start_direction = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_start_direction() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<6>(
              stream, this_._internal_start_direction(), target);
    }
  }

  // int32 face_index = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_face_index() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<7>(
              stream, this_._internal_face_index(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cam.SurfaceCalculationRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SurfaceCalculationRequest::ByteSizeLong(const MessageLite& base) {
  const SurfaceCalculationRequest& this_ = static_cast<const SurfaceCalculationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SurfaceCalculationRequest::ByteSizeLong() const {
  const SurfaceCalculationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cam.SurfaceCalculationRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // bytes step_data = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_step_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_step_data());
      }
    }
    // double step_u = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_step_u()) != 0) {
        total_size += 9;
      }
    }
    // double step_v = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_step_v()) != 0) {
        total_size += 9;
      }
    }
    // int32 toolpath_mode = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_toolpath_mode() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_toolpath_mode());
      }
    }
    // int32 num_paths = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_num_paths() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_num_paths());
      }
    }
    // int32 start_direction = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_start_direction() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_start_direction());
      }
    }
    // int32 face_index = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_face_index() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_face_index());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SurfaceCalculationRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SurfaceCalculationRequest*>(&to_msg);
  auto& from = static_cast<const SurfaceCalculationRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:cam.SurfaceCalculationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_step_data().empty()) {
        _this->_internal_set_step_data(from._internal_step_data());
      } else {
        if (_this->_impl_.step_data_.IsDefault()) {
          _this->_internal_set_step_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_step_u()) != 0) {
        _this->_impl_.step_u_ = from._impl_.step_u_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_step_v()) != 0) {
        _this->_impl_.step_v_ = from._impl_.step_v_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_toolpath_mode() != 0) {
        _this->_impl_.toolpath_mode_ = from._impl_.toolpath_mode_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_num_paths() != 0) {
        _this->_impl_.num_paths_ = from._impl_.num_paths_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_start_direction() != 0) {
        _this->_impl_.start_direction_ = from._impl_.start_direction_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_face_index() != 0) {
        _this->_impl_.face_index_ = from._impl_.face_index_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SurfaceCalculationRequest::CopyFrom(const SurfaceCalculationRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:cam.SurfaceCalculationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SurfaceCalculationRequest::InternalSwap(SurfaceCalculationRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.step_data_, &other->_impl_.step_data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.face_index_)
      + sizeof(SurfaceCalculationRequest::_impl_.face_index_)
      - PROTOBUF_FIELD_OFFSET(SurfaceCalculationRequest, _impl_.step_u_)>(
          reinterpret_cast<char*>(&_impl_.step_u_),
          reinterpret_cast<char*>(&other->_impl_.step_u_));
}

::google::protobuf::Metadata SurfaceCalculationRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CalculationResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CalculationResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CalculationResponse, _impl_._has_bits_);
};

CalculationResponse::CalculationResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CalculationResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cam.CalculationResponse)
}
PROTOBUF_NDEBUG_INLINE CalculationResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::cam::CalculationResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        raw_vertices_(arena, from.raw_vertices_) {}

CalculationResponse::CalculationResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CalculationResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CalculationResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CalculationResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.point_count_ = from._impl_.point_count_;

  // @@protoc_insertion_point(copy_constructor:cam.CalculationResponse)
}
PROTOBUF_NDEBUG_INLINE CalculationResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        raw_vertices_(arena) {}

inline void CalculationResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.point_count_ = {};
}
CalculationResponse::~CalculationResponse() {
  // @@protoc_insertion_point(destructor:cam.CalculationResponse)
  SharedDtor(*this);
}
inline void CalculationResponse::SharedDtor(MessageLite& self) {
  CalculationResponse& this_ = static_cast<CalculationResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.raw_vertices_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CalculationResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CalculationResponse(arena);
}
constexpr auto CalculationResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CalculationResponse),
                                            alignof(CalculationResponse));
}
constexpr auto CalculationResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CalculationResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CalculationResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CalculationResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CalculationResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CalculationResponse>(), &CalculationResponse::ByteSizeLong,
              &CalculationResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CalculationResponse, _impl_._cached_size_),
          false,
      },
      &CalculationResponse::kDescriptorMethods,
      &descriptor_table_cam_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CalculationResponse_class_data_ =
        CalculationResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CalculationResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CalculationResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CalculationResponse_class_data_.tc_table);
  return CalculationResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
CalculationResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CalculationResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CalculationResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cam::CalculationResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 point_count = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CalculationResponse, _impl_.point_count_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(CalculationResponse, _impl_.point_count_)}},
    // bytes raw_vertices = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CalculationResponse, _impl_.raw_vertices_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes raw_vertices = 1;
    {PROTOBUF_FIELD_OFFSET(CalculationResponse, _impl_.raw_vertices_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // int32 point_count = 2;
    {PROTOBUF_FIELD_OFFSET(CalculationResponse, _impl_.point_count_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CalculationResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:cam.CalculationResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.raw_vertices_.ClearNonDefaultToEmpty();
  }
  _impl_.point_count_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CalculationResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CalculationResponse& this_ = static_cast<const CalculationResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CalculationResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CalculationResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:cam.CalculationResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes raw_vertices = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_raw_vertices().empty()) {
      const ::std::string& _s = this_._internal_raw_vertices();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // int32 point_count = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_point_count() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_point_count(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cam.CalculationResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CalculationResponse::ByteSizeLong(const MessageLite& base) {
  const CalculationResponse& this_ = static_cast<const CalculationResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CalculationResponse::ByteSizeLong() const {
  const CalculationResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cam.CalculationResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // bytes raw_vertices = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_raw_vertices().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_raw_vertices());
      }
    }
    // int32 point_count = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_point_count() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_point_count());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CalculationResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CalculationResponse*>(&to_msg);
  auto& from = static_cast<const CalculationResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:cam.CalculationResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_raw_vertices().empty()) {
        _this->_internal_set_raw_vertices(from._internal_raw_vertices());
      } else {
        if (_this->_impl_.raw_vertices_.IsDefault()) {
          _this->_internal_set_raw_vertices("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_point_count() != 0) {
        _this->_impl_.point_count_ = from._impl_.point_count_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CalculationResponse::CopyFrom(const CalculationResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:cam.CalculationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CalculationResponse::InternalSwap(CalculationResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.raw_vertices_, &other->_impl_.raw_vertices_, arena);
  swap(_impl_.point_count_, other->_impl_.point_count_);
}

::google::protobuf::Metadata CalculationResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace cam
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_cam_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
