// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cam_service.proto
#ifndef GRPC_cam_5fservice_2eproto__INCLUDED
#define GRPC_cam_5fservice_2eproto__INCLUDED

#include "cam_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace cam {

class CamCalculationService final {
 public:
  static constexpr char const* service_full_name() {
    return "cam.CamCalculationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::cam::CalculationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>> AsyncCalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>>(AsyncCalculateToolpathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>> PrepareAsyncCalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>>(PrepareAsyncCalculateToolpathRaw(context, request, cq));
    }
    virtual ::grpc::Status CalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::cam::CalculationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>> AsyncCalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>>(AsyncCalculateSurfaceToolpathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>> PrepareAsyncCalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>>(PrepareAsyncCalculateSurfaceToolpathRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest* request, ::cam::CalculationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest* request, ::cam::CalculationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest* request, ::cam::CalculationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest* request, ::cam::CalculationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>* AsyncCalculateToolpathRaw(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>* PrepareAsyncCalculateToolpathRaw(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>* AsyncCalculateSurfaceToolpathRaw(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cam::CalculationResponse>* PrepareAsyncCalculateSurfaceToolpathRaw(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::cam::CalculationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>> AsyncCalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>>(AsyncCalculateToolpathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>> PrepareAsyncCalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>>(PrepareAsyncCalculateToolpathRaw(context, request, cq));
    }
    ::grpc::Status CalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::cam::CalculationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>> AsyncCalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>>(AsyncCalculateSurfaceToolpathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>> PrepareAsyncCalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>>(PrepareAsyncCalculateSurfaceToolpathRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest* request, ::cam::CalculationResponse* response, std::function<void(::grpc::Status)>) override;
      void CalculateToolpath(::grpc::ClientContext* context, const ::cam::CalculationRequest* request, ::cam::CalculationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest* request, ::cam::CalculationResponse* response, std::function<void(::grpc::Status)>) override;
      void CalculateSurfaceToolpath(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest* request, ::cam::CalculationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>* AsyncCalculateToolpathRaw(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>* PrepareAsyncCalculateToolpathRaw(::grpc::ClientContext* context, const ::cam::CalculationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>* AsyncCalculateSurfaceToolpathRaw(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cam::CalculationResponse>* PrepareAsyncCalculateSurfaceToolpathRaw(::grpc::ClientContext* context, const ::cam::SurfaceCalculationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CalculateToolpath_;
    const ::grpc::internal::RpcMethod rpcmethod_CalculateSurfaceToolpath_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CalculateToolpath(::grpc::ServerContext* context, const ::cam::CalculationRequest* request, ::cam::CalculationResponse* response);
    virtual ::grpc::Status CalculateSurfaceToolpath(::grpc::ServerContext* context, const ::cam::SurfaceCalculationRequest* request, ::cam::CalculationResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CalculateToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CalculateToolpath() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CalculateToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateToolpath(::grpc::ServerContext* /*context*/, const ::cam::CalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculateToolpath(::grpc::ServerContext* context, ::cam::CalculationRequest* request, ::grpc::ServerAsyncResponseWriter< ::cam::CalculationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CalculateSurfaceToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CalculateSurfaceToolpath() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CalculateSurfaceToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateSurfaceToolpath(::grpc::ServerContext* /*context*/, const ::cam::SurfaceCalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculateSurfaceToolpath(::grpc::ServerContext* context, ::cam::SurfaceCalculationRequest* request, ::grpc::ServerAsyncResponseWriter< ::cam::CalculationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CalculateToolpath<WithAsyncMethod_CalculateSurfaceToolpath<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CalculateToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CalculateToolpath() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::cam::CalculationRequest, ::cam::CalculationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cam::CalculationRequest* request, ::cam::CalculationResponse* response) { return this->CalculateToolpath(context, request, response); }));}
    void SetMessageAllocatorFor_CalculateToolpath(
        ::grpc::MessageAllocator< ::cam::CalculationRequest, ::cam::CalculationResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cam::CalculationRequest, ::cam::CalculationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CalculateToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateToolpath(::grpc::ServerContext* /*context*/, const ::cam::CalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculateToolpath(
      ::grpc::CallbackServerContext* /*context*/, const ::cam::CalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CalculateSurfaceToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CalculateSurfaceToolpath() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::cam::SurfaceCalculationRequest, ::cam::CalculationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cam::SurfaceCalculationRequest* request, ::cam::CalculationResponse* response) { return this->CalculateSurfaceToolpath(context, request, response); }));}
    void SetMessageAllocatorFor_CalculateSurfaceToolpath(
        ::grpc::MessageAllocator< ::cam::SurfaceCalculationRequest, ::cam::CalculationResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cam::SurfaceCalculationRequest, ::cam::CalculationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CalculateSurfaceToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateSurfaceToolpath(::grpc::ServerContext* /*context*/, const ::cam::SurfaceCalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculateSurfaceToolpath(
      ::grpc::CallbackServerContext* /*context*/, const ::cam::SurfaceCalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CalculateToolpath<WithCallbackMethod_CalculateSurfaceToolpath<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CalculateToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CalculateToolpath() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CalculateToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateToolpath(::grpc::ServerContext* /*context*/, const ::cam::CalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CalculateSurfaceToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CalculateSurfaceToolpath() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CalculateSurfaceToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateSurfaceToolpath(::grpc::ServerContext* /*context*/, const ::cam::SurfaceCalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CalculateToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CalculateToolpath() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CalculateToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateToolpath(::grpc::ServerContext* /*context*/, const ::cam::CalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculateToolpath(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CalculateSurfaceToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CalculateSurfaceToolpath() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CalculateSurfaceToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateSurfaceToolpath(::grpc::ServerContext* /*context*/, const ::cam::SurfaceCalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculateSurfaceToolpath(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CalculateToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CalculateToolpath() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CalculateToolpath(context, request, response); }));
    }
    ~WithRawCallbackMethod_CalculateToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateToolpath(::grpc::ServerContext* /*context*/, const ::cam::CalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculateToolpath(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CalculateSurfaceToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CalculateSurfaceToolpath() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CalculateSurfaceToolpath(context, request, response); }));
    }
    ~WithRawCallbackMethod_CalculateSurfaceToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateSurfaceToolpath(::grpc::ServerContext* /*context*/, const ::cam::SurfaceCalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculateSurfaceToolpath(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CalculateToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CalculateToolpath() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cam::CalculationRequest, ::cam::CalculationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cam::CalculationRequest, ::cam::CalculationResponse>* streamer) {
                       return this->StreamedCalculateToolpath(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CalculateToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CalculateToolpath(::grpc::ServerContext* /*context*/, const ::cam::CalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCalculateToolpath(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cam::CalculationRequest,::cam::CalculationResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CalculateSurfaceToolpath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CalculateSurfaceToolpath() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cam::SurfaceCalculationRequest, ::cam::CalculationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cam::SurfaceCalculationRequest, ::cam::CalculationResponse>* streamer) {
                       return this->StreamedCalculateSurfaceToolpath(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CalculateSurfaceToolpath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CalculateSurfaceToolpath(::grpc::ServerContext* /*context*/, const ::cam::SurfaceCalculationRequest* /*request*/, ::cam::CalculationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCalculateSurfaceToolpath(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cam::SurfaceCalculationRequest,::cam::CalculationResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CalculateToolpath<WithStreamedUnaryMethod_CalculateSurfaceToolpath<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CalculateToolpath<WithStreamedUnaryMethod_CalculateSurfaceToolpath<Service > > StreamedService;
};

}  // namespace cam


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_cam_5fservice_2eproto__INCLUDED
